server:
  port: ${GATEWAY_SERVER_PORT:4000}

spring:
  application:
    name: Gateway
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${GATEWAY_JWT_SECRET_KEY:EcEATUqDpEcc.EcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEccEcEATUqDpEcc}
          expiration: 36000

application:
  ca-name: ${GATEWAY_CA_NAME}
  key-value-store: ${GATEWAY_KEY_VALUE_STORE}
  admin-username: ${GATEWAY_ADMIN_USERNAME}
  admin-password: ${GATEWAY_ADMIN_PASSWORD}
  msp-id: ${GATEWAY_MSP_ID}
  supported-chaincodes: ${GATEWAY_SUPPORTED_CHAINCODES}
  default-chaincode: ${GATEWAY_DEFAULT_CHAINCODE}
  certificate-authorities-raw:
    1:
      id: ${GATEWAY_CA_NAME}
      url: "https://${GATEWAY_CA_URL}:${GATEWAY_CA_PORT}"
      tls-cA-certs:
        - "${GATEWAY_CRYPTO_PATH}${GATEWAY_CA_CERT_PATH}"
